version: "3.0"

services:
 nginx:
  depends_on:
   - wordpress-php
  build: ./requirements/nginx/
  image: nginx:nlee
  env_file: .env
  container_name: webserver
  ports:
   - "443:443"
#   restart: always
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - app-network

 wordpress-php:
  depends_on:
   - redis_cache
  build: ./requirements/wordpress/
  image: wordpress-php:nlee
  container_name: wordpress-php
  env_file: .env
  ports:
   - "9000"
#   restart: always
  volumes:
   - wordpress:/var/www/wordpress
  networks:
   - app-network

 redis_cache:
  depends_on:
   - mariadb
  build: ./requirements/bonus/redis/
  image: redis_cache:nlee
  container_name: redis_cache
  env_file: .env
#   restart: always
  ports:
   - "6379"
  networks:
   - app-network  

 mariadb:
  build:
   context: ./requirements/mariadb/
  image: mariadb:nlee
  env_file: .env
  container_name: mariadb
#   restart: always
  ports:
   - "3306"
  volumes:
   - dbdata:/var/lib/mysql
  restart: unless-stopped
  networks:
   - app-network

networks:
 app-network:
  driver : bridge

volumes:
 dbdata:
 wordpress:
